// Copyright (c) Tailscale Inc & contributors
// SPDX-License-Identifier: BSD-3-Clause
//
// Portions Copyright (c) BARGHEST
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This file contains code originally from Tailscale (BSD-3-Clause)
// with modifications by BARGHEST. The modified version is licensed
// under AGPL-3.0-or-later. See LICENSE for details.

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_linuxdnsfight

package buildfeatures

// HasLinuxDNSFight is whether the binary was built with support for modular feature "Linux support for detecting DNS fights (inotify watching of /etc/resolv.conf)".
// Specifically, it's whether the binary was NOT built with the "ts_omit_linuxdnsfight" build tag.
// It's a const so it can be used for dead code elimination.
const HasLinuxDNSFight = true
