// Copyright (c) 2020- 2025 Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause
// Additional contributions by BARGHEST are dedicated to the public domain under CC0 1.0.

// Code generated by gen.go; DO NOT EDIT.

//go:build !ts_omit_logtail

package buildfeatures

// HasLogTail is whether the binary was built with support for modular feature "upload logs to log.tailscale.com (debug logs for bug reports and also by network flow logs if enabled)".
// Specifically, it's whether the binary was NOT built with the "ts_omit_logtail" build tag.
// It's a const so it can be used for dead code elimination.
const HasLogTail = true
